version: '3'

services:
  notes-db:
    image: postgres:10.4
    volumes:
      - notes-db-data:/var/lib/postgresql
    env_file:
      - notes-db.env
    ports:
      - "5432:5432"
  notes-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - notes-web.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - notes-db

volumes:
  notes-db-data:
